project_name: golink

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
    - amd64
    - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: azrod
    name: golink
  draft: false

dockers:
  - image_templates:
    - "ghcr.io/azrod/{{.ProjectName}}:{{ .Version }}-amd64"
    extra_files:
      - ui/
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/azrod/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/azrod/{{.ProjectName}}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - image_templates: 
    - "ghcr.io/azrod/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    extra_files:
      - ui/
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/arm64/v8
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/azrod/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/azrod/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
docker_manifests:
- name_template: "ghcr.io/azrod/{{ .ProjectName }}:{{ .Version }}"
  image_templates:
  - "ghcr.io/azrod/{{ .ProjectName }}:{{ .Version }}-amd64"
  - "ghcr.io/azrod/{{ .ProjectName }}:{{ .Version }}-arm64v8"
- name_template: "ghcr.io/azrod/{{ .ProjectName }}:latest"
  image_templates:
  - "ghcr.io/azrod/{{ .ProjectName }}:{{ .Version }}-amd64"
  - "ghcr.io/azrod/{{ .ProjectName }}:{{ .Version }}-arm64v8"
