project_name: golink

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

builds:
  - id: "golink"
    binary: golink
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
  - id: "glctl"
    binary: glctl
    main: ./cmd/glctl
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64

dockers:
  - goarch: amd64 
    image_templates:
    - "ghcr.io/azrod/{{.ProjectName}}:v{{ .Version }}-amd64"
    extra_files:
      - ui/
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/azrod/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/azrod/{{.ProjectName}}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}

  - goarch: arm64
    image_templates: 
    - "ghcr.io/azrod/{{ .ProjectName }}:v{{ .Version }}-arm64v8"
    extra_files:
      - ui/
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/arm64/v8
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/azrod/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/azrod/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}

  - goarch: arm
    image_templates: 
    - "ghcr.io/azrod/{{ .ProjectName }}:v{{ .Version }}-armv7"
    extra_files:
      - ui/
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/arm/v7
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/azrod/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/azrod/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}

docker_manifests:
- name_template: "ghcr.io/azrod/{{ .ProjectName }}:v{{ .Version }}"
  image_templates:
  - "ghcr.io/azrod/{{ .ProjectName }}:v{{ .Version }}-amd64"
  - "ghcr.io/azrod/{{ .ProjectName }}:v{{ .Version }}-arm64v8"
  - "ghcr.io/azrod/{{ .ProjectName }}:v{{ .Version }}-armv7"
- name_template: "ghcr.io/azrod/{{ .ProjectName }}:latest"
  image_templates:
  - "ghcr.io/azrod/{{ .ProjectName }}:v{{ .Version }}-amd64"
  - "ghcr.io/azrod/{{ .ProjectName }}:v{{ .Version }}-arm64v8"
  - "ghcr.io/azrod/{{ .ProjectName }}:v{{ .Version }}-armv7"

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md