project_name: golink

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

release:
  prerelease: auto


snapshot:
  version_template: "{{ .Tag }}"

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

builds:
  - id: "golink"
    binary: golink
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
  - id: "glctl"
    binary: glctl
    main: ./cmd/glctl
    ldflags:
      - '-s -w -X github.com/azrod/golink/cmd/glctl/cmd.version={{.Version}} -X github.com/azrod/golink/cmd/glctl/cmd.commit={{.Commit}} -X github.com/azrod/golink/cmd/glctl/cmd.date={{.Date}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0

dockers:
  - goarch: amd64 
    image_templates:
    - "ghcr.io/azrod/{{.ProjectName}}:v{{ .Version }}-amd64"
    extra_files:
      - ui/
    dockerfile: Dockerfile
    use: buildx
    ids:
      - golink
      - glctl
    build_flag_templates:
    - --platform=linux/amd64
    - --pull
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/azrod/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/azrod/{{.ProjectName}}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}

  - goarch: arm64
    image_templates: 
    - "ghcr.io/azrod/{{ .ProjectName }}:v{{ .Version }}-arm64v8"
    extra_files:
      - ui/
    dockerfile: Dockerfile
    use: buildx
    ids:
      - golink
      - glctl
    build_flag_templates:
    - --platform=linux/arm64/v8
    - --pull
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/azrod/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/azrod/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}

docker_manifests:
- name_template: "ghcr.io/azrod/{{ .ProjectName }}:v{{ .Version }}"
  image_templates:
  - "ghcr.io/azrod/{{ .ProjectName }}:v{{ .Version }}-amd64"
  - "ghcr.io/azrod/{{ .ProjectName }}:v{{ .Version }}-arm64v8"
- name_template: "ghcr.io/azrod/{{ .ProjectName }}:latest"
  image_templates:
  - "ghcr.io/azrod/{{ .ProjectName }}:v{{ .Version }}-amd64"
  - "ghcr.io/azrod/{{ .ProjectName }}:v{{ .Version }}-arm64v8"

archives:
  # Golink
  - id: "golink"
    builds:
      - golink
    format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: 'golink-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md
  # glctl
  - id: "glctl"
    builds:
      - glctl
    format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: 'glctl-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - ./cmd/glctl/README.md