site_name: GoLink Documentation

theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - header.autohide
    - navigation.instant
  icon:
    repo: fontawesome/brands/github-alt
  # favicon: images/favicon.png
  # logo: images/logo.png
  font: false


extra_css:
  - stylesheets/extra.css

plugins:
  - search

nav:
  - Overview: "index.md"
  - Deployment:
    - "Getting Start": "deployment/getting-start.md"
    - "Docker": "deployment/docker.md"
  - glctl (CLI):
    - "Install": "glctl/install.md"

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde



extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/azrod/golink
  
copyright: Copyright &copy; 2023 - 2024 azrod