version: 1

project_name: glctl

# before:
#   hooks:
#     # You may remove this if you don't use go modules.
#     - go mod tidy
#     # you may remove this if you don't need go generate
#     - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
      # Default: [ 'darwin', 'linux', 'windows' ]
      # Default: [ '386', 'amd64', 'arm64' ]
    binary: '{{ .ProjectName }}_{{ .Version }}'

universal_binaries:
  - replace: true

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}'
    maintainer: https://github.com/azrod
    package_name: golinkctl
    description: >-
      golinkctl is a command line tool to manage golink
    homepage: https://github.com/azrod/golink
    license: Apache-2.0
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux 
    bindir: /usr/bin
    section: default

brews:
  - name: '{{ .ProjectName }}'
    homepage: hhttps://github.com/azrod/golink/cmd
    goarm: 6
    goamd64: v1
    repository: 
      owner: azrod
      name: '{{ .ProjectName }}'
      branch: main

archives:
  - format: zip
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
